# Generated by Django 4.2.16 on 2024-09-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='plate',
            unique_together={('client', 'registration')},
        ),
    ]
